# Generated by Django 5.2.17 on 2026-09-08 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(db_index=True)),
                ('rating', models.CharField(choices=[('up', 'Helpful'), ('down', 'Not helpful')], max_length=8)),
                ('category', models.CharField(blank=True, default='', max_length=64)),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedback',
                'db_table': 'chat_feedback',
                'ordering': ['-created_at'],
            },
        ),
    ]
